### ISSUE TITLE
Todo: release 1.0.1 on Rubygems.org

### ISSUE THREAD

**Issue by kurko** [cfis/proj4rb#12]
1.0.1 fixes compilation problems with news versions of Proj.

**Comment by cfis** [comment]
After getting up to speed on new version of Proj, I don't think its worth doing a point release. Instead, I've rewritten the gem to use the new apis in Proj5 and Proj6 (and also maintain backwards compatibility  for existing code).

So going to close this ticket and instead release version 2 of the gem shortly.

**Comment by kurko** [comment]
🙇‍♂️

**Comment by ioquatix** [comment]
You released 2.0.0 which only supports ruby 2.4.9 - is there some reason for this? We are stuck on Ruby 2.4.1 which I'll try to fix on my end, but was there any reason to prevent a 1.0.1 release supporting 2.4?

**Comment by cfis** [comment]
Just went with the oldest currently supported version of Ruby. 2.4.x is fine by me.

**Comment by cfis** [comment]
Also thanks for the other fixes.
