### ISSUE TITLE
Problems with proj v6

### ISSUE THREAD

**Issue by jklimke** [cfis/proj4rb#16]
Hi,

i tried to install and use the gem with  proj >= 6.0.0

First i noticed that the versions 6.1.0, 6.1.1, 6.2.0, and 6.2.1 are not supported due to the missing entries for the corresponding libraries in the api.rb. The profix of these versions is 16, 17, 18 and 19. So that installed libraries cannot be found. Is this on purpose or are they just missing ?
 
Second, i managed to install the gem but on ```require "proj4"``` with proj lib version 15 i get a missing function ```proj_as_projjson``` which was actually added in 6.2.0. Did i miss anything here ?

```
2.6.4 :001 > require "proj4"
Traceback (most recent call last):
       16: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
       15: from (irb):1
       14: from /usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
       13: from /usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
       12: from /usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
       11: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/proj4.rb:4:in `<top (required)>'
       10: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/proj4.rb:4:in `require_relative'
        9: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/proj.rb:3:in `<top (required)>'
        8: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/proj.rb:3:in `require_relative'
        7: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/api/api.rb:3:in `<top (required)>'
        6: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/api/api.rb:54:in `<module:Proj>'
        5: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/api/api.rb:54:in `require_relative'
        4: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/api/api_6_0.rb:1:in `<top (required)>'
        3: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/api/api_6_0.rb:2:in `<module:Proj>'
        2: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/proj4rb-2.2.0/lib/api/api_6_0.rb:23:in `<module:Api>'
        1: from /usr/local/rvm/gems/ruby-2.6.4@tasa/gems/ffi-1.11.3/lib/ffi/library.rb:273:in `attach_function'
FFI::NotFoundError (Function 'proj_as_projjson' not found in [/usr/local/lib/libproj.so.15])
2.6.4 :002 >
```

**Comment by ioquatix** [comment]
Please feel free to submit a PR.

**Comment by cfis** [comment]
Thanks for the heads up on proj_as_projjson, its now moved from the 6.0 api to the 6.2 api file. I tried to get these right, but sometimes its not quite so obvious when a function was introduced.

The other things that isn't so obvious is the proj shared library version. On my machine, using mingw64, version 15 is proj 6.2. I saw the same thing on Fedora Linux and Macports.  From the traceback, you have version libproj15 but for you that's apparently version 6.0. How is that possible?  Did you build it yourself by chance?

Anyway, I've never seen versions 16/17/18/19.  Do you know of some reference that details how proj versions related to the shared library version? I haven't seen one on the proj.org website but maybe I'm just missing it?. Guess I have to go through the git history.

**Comment by ioquatix** [comment]
Just a quick note, we compile Proj from source for our production environment, and we added `libproj` just by itself to `ffi_lib`... because it wasn't versioned. Maybe a good idea to add that as a default?

**Comment by cfis** [comment]
So I had it originally and then later removed it because I never saw that one in the wild either.  But sure, you can add it in.

Note I just changed that search paths code to split the versions from the different OS file patterns.  So you can add in that new pattern, but then you'll need an ugly check to see the number of % in the string format pattern (in your case 0). Kind of ugly, I'm sure there is a better way?

I just didn't want to have to repeat all the file names over and over for versions 16, 17, 18, etc.

**Comment by cfis** [comment]
Ok, the version info is in this file:

**Comment by jklimke** [comment]
@cfis you were right i built it myself. I was just preparing a pull request which basically did the same than your changes to the code. Thanks for the changes and the discussion.

**Comment by cfis** [comment]
I'm now thinking we should have a  def windows_path method, def mac_os_paths, etc.  Just so we don't have FFI search for 20 different files at startup.
