### ISSUE TITLE
FFI gem ver >= 13 cannot load proj

### ISSUE THREAD

**Issue by isaacrowntree** [cfis/proj4rb#19]
To reproduce try

```
require 'proj'
```

Run the file. FFI versions greater than 12 throw an error related to these changes in the FFI gem:

Changelog for version 1.13.0: 

`Reject callback with :string return type at definition, because it didn't work so far and is not save to use. #751, #782`

Links to issues:

https://github.com/ffi/ffi/issues/751
https://github.com/ffi/ffi/pull/782

**Comment by cfis** [comment]
Hmm, ok, Do you know what callback is causing the error? Want to submit a patch?

**Comment by cuirc** [comment]
Looks like it's triggered by proj_file_finder
