### ISSUE TITLE
using PROJ version > 7.2.1 results in pj_init "not found" error

### ISSUE THREAD

**Issue by dougq** [cfis/proj4rb#20]
It appears that using a PROJ version > 7.2.1 results in pj_init "not found" error; Homebrew upgraded PROJ from 7.2.1 to 8.1.1 and error appeared. It went away when I downgraded to 7.2.1. 

Maybe a result of this?

"Attention: The proj_api.h header and the functions related to it is considered deprecated from version 5.0.0
and onwards. The header has been removed in version 8.0.0 released March 1st 2021." (from p. 604 of "PROJ coordinate transformation software library" at

https://raw.githubusercontent.com/OSGeo/proj.4/gh-pages/proj.pdf

**Comment by cfis** [comment]
Yes, that seems likely. Thanks for the report.

**Comment by cfis** [comment]
Fixed in 9b4ca91840997fc15f3032b3ccb38815c7c9386b.

**Comment by isaacrowntree** [comment]
Thank you!
