### ISSUE TITLE
Can not compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by ldesousa** [cfis/proj4rb#6]
I tried to follow the install instructions for Linux, but none of the methods succeeded. The log goes below.

$ cd ~/temp/ruby/proj4rb-1.0.0
$ ls -la
total 56
drwx------ 7 desousa desousa 4096 Feb 24 09:59 .
drwxrwxr-x 3 desousa desousa 4096 Feb 24 10:00 ..
-rw-rw-r-- 1 desousa desousa 1050 Dec 15 04:13 ChangeLog
drwx------ 2 desousa desousa 4096 Feb 24 09:59 data
drwx------ 2 desousa desousa 4096 Feb 24 09:59 example
drwx------ 3 desousa desousa 4096 Feb 24 09:59 ext
-rw-rw-r-- 1 desousa desousa   86 Dec 15 04:13 .gitignore
drwx------ 2 desousa desousa 4096 Feb 24 09:59 lib
-rw-rw-r-- 1 desousa desousa 1130 Dec 15 04:13 MIT-LICENSE
-rw-rw-r-- 1 desousa desousa 1068 Dec 15 04:13 proj4rb.gemspec
-rw-rw-r-- 1 desousa desousa 1020 Dec 15 04:13 Rakefile
-rw-rw-r-- 1 desousa desousa 6211 Dec 15 04:13 README.rdoc
drwx------ 2 desousa desousa 4096 Feb 24 09:59 test

$ rake build --trace
rake aborted!
Don't know how to build task 'build'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/task_manager.rb:62:in `[]'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:149:in`invoke_task'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:106:in`each'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:115:in`run_with_threads'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:78:in`block in run'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/lib/rake/application.rb:75:in`run'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/bin/rake:23:in`load'
/home/desousa/.rvm/gems/ruby-1.9.2-p290/bin/rake:23:in `<main>'

$ cd ext
$ ruby extconf.rb
checking for proj_api.h... yes
checking for projects.h... yes
checking for pj_init() in -lproj... yes
creating Makefile
$ make
gcc -I. -I/home/desousa/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/x86_64-linux -I/home/desousa/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/desousa/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_PROJ_API_H -DHAVE_PROJECTS_H    -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC  -o projrb.o -c projrb.c
In file included from /usr/local/include/projects.h:244:0,
                 from projrb.c:3:
/usr/include/proj_api.h:61:5: error: unknown type name ‘projCtx_t’
     typedef projCtx_t _projCtx;
     ^
make: *_\* [projrb.o] Error 1

**Comment by cfis** [comment]
Sorry for never getting back on this one. Version 2.0.0 uses FFI so this is no longer an issue.
