### ISSUE TITLE
Environment variable PROJ_LIB overwritten 

### ISSUE THREAD

**Issue by pdean** [cfis/proj4rb#7]
Program should test that PROJ_LIB doesn't already exist before changing it.  It points to the folder where custom files are stored.

**Comment by pdean** [comment]
A workaround is to save the current value before requiring, then set it back after. Here's an example where proj needs PROJ_LIB to find ausgeoid09.gtx

projlib=ENV['PROJ_LIB']
require 'proj4'
include Proj4
ENV['PROJ_LIB']=projlib

mga56=Projection.new "+proj=utm +zone=56 +south +ellps=GRS80 \
  +geoidgrids=ausgeoid09.gtx" 
gda94=Projection.new "+proj=latlon +axis=neu +ellps=GRS80"
point = Point.new(502810, 6964520, 0)
res = mga56.transform(gda94,point)
puts "x=#{point.x}, y=#{point.y} ==> \
lat=#{res.x*RAD_TO_DEG}, lon=#{res.y*RAD_TO_DEG}, \
z=#{res.z}"

**Comment by cfis** [comment]
Agreed, this is fixed in version 2.0.0
