### ISSUE TITLE
When using macports, you must specify the directory explicitly

### ISSUE THREAD

**Issue by ioquatix** [cfis/proj4rb#8]
After doing:

```
sudo port install proj4
```

to install the gem I needed to do:

```
gem install proj4rb -- --with-cflags="-I/opt/local/lib/proj49/include/" --with-ldflags="-L/opt/local/lib/proj49/lib/"
```

Is this normal? Should we add this to the README?

**Comment by cfis** [comment]
Depends I think on if you are using the built-in ruby (in that case yes you have to specify the -I) or the macports version of Ruby (in which case I'm guessing you don't).

**Comment by ioquatix** [comment]
I'm using RVM with is super common. I think adding this to the README might be useful.
